# Generated by Django 5.0.2 on 2025-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
    ]
