# Generated by Django 5.0.2 on 2025-05-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('self_assessment', models.TextField(blank=True)),
                ('team_lead_feedback', models.TextField(blank=True)),
                ('manager_feedback', models.TextField(blank=True)),
                ('senior_manager_feedback', models.TextField(blank=True)),
                ('hr_feedback', models.TextField(blank=True)),
                ('self_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('team_lead_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('senior_manager_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('final_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('self_review', 'Self Review'), ('team_lead_review', 'Team Lead Review'), ('manager_review', 'Manager Review'), ('senior_manager_review', 'Senior Manager Review'), ('hr_review', 'HR Review'), ('completed', 'Completed')], default='draft', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-review_period_end'],
            },
        ),
    ]
