# Generated by Django 5.0.2 on 2025-05-03 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentplan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpireview',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.kpi'),
        ),
        migrations.AlterUniqueTogether(
            name='performancecycle',
            unique_together={('name', 'start_date')},
        ),
        migrations.AddField(
            model_name='performancegoal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.performancecycle'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpireview',
            name='performance_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_reviews', to='performance.performancereview'),
        ),
        migrations.AddField(
            model_name='developmentplan',
            name='performance_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to='performance.performancereview'),
        ),
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together={('employee', 'cycle')},
        ),
        migrations.AlterUniqueTogether(
            name='kpireview',
            unique_together={('performance_review', 'kpi')},
        ),
    ]
