# Generated by Django 5.0.2 on 2025-05-03 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrecord'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarystructure'),
        ),
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarystructure'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='components',
            field=models.ManyToManyField(through='payroll.SalaryStructureComponent', to='payroll.salarycomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together={('employee', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='salarystructurecomponent',
            unique_together={('salary_structure', 'component')},
        ),
    ]
